### PR TITLE
Use fallback for wait() from ember-test-helpers

### PR DESCRIPTION
**Pull request by YoranBrondsema**
Solves https://github.com/san650/ember-cli-page-object/issues/309.

### CODE REVIEW

**Comment by san650** [comment]
Please, see my questions in #309

**Comment by san650** [comment]
@YoranBrondsema Thank you for taking the time to work on this PR.

I'll try to review and test this PR thoroughly over the next weekend. I don't want to introduce breaking changes and ensure we support older versions of ember.

**Comment by YoranBrondsema** [comment]
@san650 Of course, I appreciate you looking into this!

**Comment by san650** [comment]
Thanks for the contribution and sorry for the delay in merging this!

**Comment by YoranBrondsema** [comment]
@san650 No problem, thanks for merging!

**Comment by YoranBrondsema** [comment]
@san650 Do you mind releasing a patch release to get this in? Then I can remove the hacks I've been adding to my test suite :-)

**Comment by san650** [comment]
@YoranBrondsema I'll do this today!

Thanks for the reminder (I forgot about it 😞 ).

**Comment by YoranBrondsema** [comment]
Don't worry about it, thanks for the prompt reply!

**Comment by simonihmig** [comment]
> I'll do this today!

@san650 today is already 12 days ago 😝  Just ran into this as well, would appreciate a bug fix release as well!

**Comment by san650** [comment]
@YoranBrondsema @simonihmig Sorry about this, I didn't want to do a release because for some reason the build started to fail with ember@canary and wanted to double check first. I have some free time next weekend to look into this, if I can't fix the issue, I'll just cherry-pick this PR and release a patch version.

Sorry for the delay!

**Comment by simonihmig** [comment]
@san650 No problem! Just wanted to have a look at the failing build you mentioned, but I see all the latest builds all green!? https://travis-ci.org/san650/ember-cli-page-object/builds/249460658

**Comment by san650** [comment]
@simonihmig I'll fire a rebuild in travis. I got the failings in my local dev env when I was about to publish.

Come back to you in a sec.

**Comment by san650** [comment]
@simonihmig I run the tests in travis-ci and everything is green, ember@canary still fails locally, so there's something strange there.

https://travis-ci.org/san650/ember-cli-page-object/builds/249460658

Because it's ember@canary the one that fails, I'll release the version now and investigate later what the problem is.

**Comment by san650** [comment]
https://github.com/san650/ember-cli-page-object/issues/320

**Pull request merged**
