### PR TITLE
Adds $ declaration to all files where $ is used without Ember. prefix

### PR DESCRIPTION
**Pull request by mkeemon**
This replaces all references to the global `$` with `Ember.$`

### CODE REVIEW

**Comment by san650** [comment]
Hey @mkeemon, I noticed that you merged this branch onto your `v0.11.x` branch. We're still maintaining v0.11.x branch so if you want to push this changes upstream, it would be great 😄 . I can do a hotfix release (v0.11.3)

**Comment by TripWar** [comment]
@san650 - @mkeemon was making a quick fix for our company to solve a problem we ran into with jQuery.noConflict mode. I was going to make sure he opened PR into the main branch just to make sure this got back into the main. I'll make sure he makes the PR tomorrow. Thanks for reaching out.

**Comment by TripWar** [comment]
@san650 - PR is back open and should be ready for merge.

**Comment by san650** [comment]
@TripWar thanks, I'll take a look at it later today.

**Comment by san650** [comment]
Released as v0.11.3 See https://github.com/san650/ember-cli-page-object/releases/tag/v0.11.3

**Comment by san650** [comment]
Thanks @mkeemon and @TripWar for contributing!

**Pull request merged**
