### PR TITLE
Add option to avoid text normalization

### PR DESCRIPTION
**Pull request by vvscode**
For https://github.com/san650/ember-cli-page-object/issues/158

### CODE REVIEW

**Comment by san650** [comment]
This is great! Can you add a line of comment [here](https://github.com/vvscode/js--ember-cli-page-object/blob/issue-158--option-to-avoid-text-normalization/test-support/page-object/queries/text.js#L57-L61) explaining what the new option does?

**Comment by vvscode** [comment]
@san650  sure. Done

**Comment by san650** [comment]
Cool, thanks!

**Comment by juanazam** [comment]
@vvscode this feature is included on `v1.12.0`, cheers and thanks!

**Pull request merged**
