### PR TITLE
[WIP] New site

### PR DESCRIPTION
**Pull request by Axxiss**
To do

* [Add pages for API section](https://github.com/san650/ember-cli-page-object/blob/master/DOCUMENTATION.md)
  - [x] Setup
  - [x] Predicates
  - [x] Queries
  - [x] Actions
  - [x] Components
  - [x] Attribute options
  - [x] Scopes
  - [x] Default behavior
- [x] Improve website design (I'll split this on several specific tasks)
- [ ] Review all content (I'll split this on several specific tasks)
- [x] Add github link (image button) on the header

Nice to have
- [ ] Configure pygment or look for an alternative that highlights correctly handlebars (HTMLBars) and ES6
- [ ] Add a cheatsheet (as an image and as HTML)
- [x] Add a changelog page with references to the release pages (or just a link to releases :D)
- [ ] Add a badge or something that indicates which is the latests version (like v0.10) with a link to the release note

### CODE REVIEW

**Comment by san650** [comment]
I've made some little changes

* added a simple header and a footer, we can change them later
* changed the styles of the `pre code` blocks to make them have less contrast
* added headers to left nav-bar to differentiate the sections

Here's an screenshot of how it's looking for now

screen shot 2015-12-05 at 11 20 13 am

**Comment by san650** [comment]
A couple of screenshots of how it's looking right now

screen shot 2015-12-05 at 1 03 21 pm
screen shot 2015-12-05 at 1 03 13 pm

**Comment by san650** [comment]
Ok, so I think we have the minimum to go live with the site

Here are some screenshots

screen shot 2015-12-05 at 3 23 17 pm
screen shot 2015-12-05 at 3 23 04 pm
screen shot 2015-12-05 at 3 22 50 pm

**Comment by san650** [comment]
@juanazam @Axxiss ^^ What do you think?

**Comment by Axxiss** [comment]
I like the header matching ember-cli page style, it has a clean look and feel. I would add some small contrast (different background color) between content section and sidebar.

Contribute section is what I dislike the most.

I don't like where the section is placed, I see the sidebar as a navigation tool for the site. I would expect that contribute links shows a page on the site as 'getting sarted' and 'api references' does, but it doesn't. I would create a page with contribution info or move those links somewhere else.

Also, npm, ember observer and release notes links are out of scope under Contribute section, I would refactor it into something like this.

#### Contribute
- Github
- Bugs
- Feature Request

#### Links?
- npm
- ember observer

**Pull request merged**
