### PR TITLE
First attempt at asserting single element matchings

### PR DESCRIPTION
**Pull request by juanazam**
This PR attempts to show some code of how #56 could be implemented trying to maintain backwards compatibility with the old behavior by using an override options.

I would like to hear @san650 and @machty input on this.

Cheers!

### CODE REVIEW

**Comment by san650** [comment]
@juanazam I think it would be easier to target this PR to milestone [v1.0](https://github.com/san650/ember-cli-page-object/milestones/v1.0) which won't require backward compatibility support.

**Comment by machty** [comment]
Sorry for not piping up sooner but this looks good to me!

**Comment by san650** [comment]
Implemented in #91

**Comment by machty** [comment]
nice :)

**Pull request closed without merging**
