### PR TITLE
FIX - Root Element Lookup Not Context Lookup

### PR DESCRIPTION
**Pull request by rtablada**

### CODE REVIEW

**Comment by rtablada** [comment]
When using `getElements` to reproduce the behavior of `@ember/test-helpers` then `findElements` needs to use `getRootElement` otherwise the context for acceptance tests is the inner HTML element and not the test container Ember application.

This causes issues with things like ember-modal-dialog and other top level wormholes that would usually be found by `find` and the Ember test helpers but are failing with ember-cli-page-object.

**Comment by bendemboski** [comment]
I'm 👍 on the PR, but have a point of clarification. I believe that this will change the behavior of formerly-integration tests, while preserving the behavior of formerly-acceptance tests.

What I mean is that the legacy integration context uses the equivalent of [this.$(selector)](https://github.com/san650/ember-cli-page-object/blob/568074dc9fca9479b009e568073e5aa437b7e23f/addon-test-support/-private/execution_context/integration.js#L142) to find elements, so without specifying a custom `testContainer` integration tests _would not_ find content inside the root element but outside `this.element`. The legacy acceptance context uses the old `find()` helper, which searches inside the application's root element -- the equivalent of [$(selector, getRootElement())](https://github.com/emberjs/ember.js/blob/cafbae485d2459b95fcca4301f7a63ad395701d3/packages/ember-testing/lib/helpers/find.js#L38), so without specifying a custom `testContainer`, acceptance tests _would_ find content inside the root element but outside `this.element`.

With RFC232/268, we only have one execution context, and it currently searches inside `this.element`, which matches the behavior of the legacy integration test context. This PR changes it to search inside `getRootElement()`, which matches the legacy acceptance test context.

It has to differ in behavior from either the legacy acceptance test context or the legacy integration test context, and I think searching inside `getRootElement()` is the better way to do it, especially because that matches the behavior of [@ember/test-helpers](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/-get-element.ts#L20), and I believe of `qunit-dom`.

But I think it's worth mentioning and considering that this will change the behavior of formerly-integration tests. I'm not sure if it's worth putting in some documentation somewhere, since the only test failures I could think of that this change would cause would be if a test were depending on _not_ finding an element inside the root but outside `this.element`...

**Comment by rtablada** [comment]
For integration tests this should still work. If you set the context for the test using `page.setContext` then nothing will change with this PR since it only changes the behavior of the `else` when the context is not changed.

We have both acceptance and integration tests running with this so I will double check that everything is fine.

As far as compatibility with `setupApplicationTest` and `setupRenderingTest`, the `find`, `click` etc, from `@ember/test-helpers` are always pinned to `getRootElement`

**Comment by bendemboski** [comment]
Oh sorry, I wasn't clear -- I meant across an update. So if you update an integration test from old-style to RFC232-style without changing your page objects, then they will behave different with this PR, whereas previously they would have behaved the same (and the reverse is true of updating acceptance tests).

Existing legacy integration tests won't change (although existing RFC232/268 tests _will_ change, but not in a way that is very likely to break anything.)

**Comment by rtablada** [comment]
@bendemboski just checked.

We updated all of our integration tests to the 232 style and after this change there was not a behavior shift.

We are being explicit and setting the page context as outlined in this suggested enhancement: https://github.com/san650/ember-cli-page-object/issues/444

**Comment by ro0gr** [comment]
LGTM, will test it in few apps tomorrow.

**Comment by ro0gr** [comment]
Published as v1.15.2 🎉 

Thank you guys!

**Pull request merged**
