### PR TITLE
Use Ember.assign if possible. Otherwise use Ember.merge

### PR DESCRIPTION
**Pull request by vvscode**
https://github.com/san650/ember-cli-page-object/issues/153

### CODE REVIEW

**Comment by vvscode** [comment]
We still have DEPRECATION notices from dependencies

**Comment by san650** [comment]
Thanks @vvscode for contributing!

**Comment by san650** [comment]
@vvscode can you add update AUTHORS file?

**Comment by vvscode** [comment]
@san650  done )

**Comment by vvscode** [comment]
https://github.com/san650/ember-cli-page-object/issues/153

**Comment by san650** [comment]
Thanks!

**Pull request merged**
