### PR TITLE
Add .property property

### LINKED ISSUE #112: [Feature] .property query
I find myself having to write this sort of thing a lot:

```js
assert.equal(page.foo.attribute('disabled'), 'disabled');
```

It would be good to have a `.property` query to check for element boolean properties, ex.:

```js
assert.ok(page.foo.property('disabled'));
```

### PR DESCRIPTION
**Pull request by san650**
Fixes #112

### CODE REVIEW

**Comment by san650** [comment]
@juanazam @jeradg ready for code review

**Comment by jeradg** [comment]
@san650: There's a typo in your commit. In `addon/index.js`:

```
import { proeprty }    from './queries/property';         export { property };
```

**Comment by jeradg** [comment]
@san650: Probably means that we need to test that the exports from `addon/index.js` actually work.

**Comment by san650** [comment]
I'll add a test for it

**Pull request merged**
