### PR TITLE
V2 beta

### PR DESCRIPTION
**Pull request by ro0gr**

### CODE REVIEW

**Comment by jrjohnson** [comment]
I've got a bunch of time before the end of the year to spend on open source work, I'd be happy to help with anything you need to move v2 out the door @ro0gr. It sounds like from #359 you mostly have it locally, but let me know if there's anything I can do to help or test.

**Comment by ro0gr** [comment]
@jrjohnson Hey 👋 First, sorry for that huge delay.. And I really appreciate your will to help here!

So as I said before there is a PR containing a different efforts(it's not public https://github.com/san650/ember-cli-page-object/pull/556). The ember upgrade part is definitely incoimplete(but contains a lot of tests cleanup), so I think it's the best candidate to be extracted into a dedicated PR. We could even go a step further and upgrade to ember-source@4. Meanwhile, I'm currently focused to make embroider really work. 

I understand the year is almost over, you are probably busy with some other activity. However, if you are still interested, feel free to reach me in the ember discord for the further coordination!

**Comment by ro0gr** [comment]
@SergeAstapov, yes, with the #560 on board I'm going to finish my embroider effort(#556), and that's when I plan to drop the `ember-cli-node-assets` for sure. 

As for the `ember-native-dom-helpers`, it should be removed together with the moduleFor adapters removal, which is also planned to be done after the #560(TBH it could be done independently of the ember@3.28 PR, but at the moment it seems reasonable to me to move the ember@3.28 to the finish line first).

**Comment by jrjohnson** [comment]
Just as a data point: Update from beta.3 to beta.3 was smooth for us, no problems to report.

**Comment by jrjohnson** [comment]
updated to beta.5, equally uneventful ✅

**Comment by jrjohnson** [comment]
🎉 awesome work @ro0gr!

**Pull request merged**
